#!/usr/bin/env python3
"""Oracle values for kerr-equatorial's geodesic integrator, from KerrGeoPy.

KerrGeoPy (Black Hole Perturbation Toolkit, https://github.com/BlackHolePerturbationToolkit/kerrgeopy)
solves bound Kerr geodesics in closed form: Jacobi elliptic functions of Mino time, after Fujita
and Hikida (2009). No ODE is stepped, so there is no discretisation error in its answers and no
code in common with this crate.

It works in Boyer-Lindquist coordinates and this crate in ingoing Kerr coordinates. The two share
r, and their t and phi differ by functions of r alone,

    t = t_BL + int 2 M r / Delta dr,     phi = phi_BL + int a / Delta dr,

so over one complete radial cycle, apoapsis to apoapsis, the differences cancel. What an
equatorial bound orbit of semi-latus rectum p and eccentricity e accumulates over that cycle is
therefore the same in both charts, and is what this script prints for each orbit:

    E, L            the constants of motion belonging to (a, p, e)
    r_min, r_max    p / (1 + e) and p / (1 - e)
    d_phi           azimuth swept per radial cycle,        2 pi Upsilon_phi / Upsilon_r
    d_t             coordinate time per radial cycle,      2 pi Gamma / Upsilon_r
    d_tau           proper time per radial cycle,          int r(lambda)^2 d lambda

(d tau = Sigma d lambda defines Mino time, and Sigma = r^2 on the equatorial plane. KerrGeoPy does
not return d_tau itself, so it is the quadrature of KerrGeoPy's own closed-form r(lambda).)

Run it from the crate directory, once, and whenever the orbits change:

    python scripts/kerrgeopy_bound_orbits.py > tests/data/kerrgeopy_bound_orbits.rs

`tests/kerrgeopy_orbits.rs` includes that file and holds the integrator to it. Needs KerrGeoPy
and SciPy (`pip install kerrgeopy`); written against KerrGeoPy 0.9.3. M = 1 throughout, which is
all KerrGeoPy's natural units offer.
"""

import sys
from math import pi

import kerrgeopy
from scipy.integrate import quad

# (a, p, e, x): x = +1 prograde, -1 retrograde. A mild orbit, a zoom-whirl close to its separatrix
# (nearly two turns of azimuth per radial cycle), the same hole run backwards, a near-extremal hole
# with a periapsis inside the ergosphere, and Schwarzschild.
ORBITS = [
    (0.9, 6.0, 0.5, 1),
    (0.9, 3.0, 0.4, 1),
    (0.9, 12.0, 0.3, -1),
    (0.998, 2.4, 0.3, 1),
    (0.0, 8.0, 0.5, 1),
]


def main():
    print("// Generated by scripts/kerrgeopy_bound_orbits.py - do not edit by hand.")
    print("//")
    print("// Bound equatorial Kerr geodesics solved in closed form by KerrGeoPy, M = 1: the constants of")
    print("// motion of each (a, p, e), its turning points, and the azimuth, coordinate time and proper")
    print("// time it accumulates over one radial cycle, which are the same in Boyer-Lindquist and in")
    print("// ingoing Kerr coordinates.")
    print("pub const ORBITS: &[OracleOrbit] = &[")
    for a, p, e, x in ORBITS:
        orbit = kerrgeopy.StableOrbit(a, p, e, x)
        energy, l_ang, carter = orbit.constants_of_motion()
        assert carter == 0.0, "an equatorial orbit has no Carter constant"
        ups_r, _, ups_phi, gamma = orbit.mino_frequencies()
        _, r_of, _, _ = orbit.trajectory()
        mino_period = 2 * pi / ups_r
        d_tau, err = quad(lambda lam: r_of(lam) ** 2, 0.0, mino_period, epsabs=1e-13, epsrel=1e-13, limit=400)
        assert err < 1e-10, f"quadrature of r^2 only good to {err}"
        print(f"    // a = {a}, p = {p}, e = {e}, {'prograde' if x > 0 else 'retrograde'}", file=sys.stdout)
        print("    OracleOrbit {")
        print(f"        a: {float(a)!r}, energy: {float(energy)!r}, l_ang: {float(l_ang)!r},")
        print(f"        r_min: {p / (1 + e)!r}, r_max: {p / (1 - e)!r},")
        print(f"        d_phi: {float(2 * pi * ups_phi / ups_r)!r},")
        print(f"        d_t: {float(2 * pi * gamma / ups_r)!r},")
        print(f"        d_tau: {float(d_tau)!r},")
        print("    },")
    print("];")


if __name__ == "__main__":
    main()
