// Generated by scripts/kerrgeopy_bound_orbits.py - do not edit by hand.
//
// Bound equatorial Kerr geodesics solved in closed form by KerrGeoPy, M = 1: the constants of
// motion of each (a, p, e), its turning points, and the azimuth, coordinate time and proper
// time it accumulates over one radial cycle, which are the same in Boyer-Lindquist and in
// ingoing Kerr coordinates.
pub const ORBITS: &[OracleOrbit] = &[
    // a = 0.9, p = 6.0, e = 0.5, prograde
    OracleOrbit {
        a: 0.9, energy: 0.9409177840177981, l_ang: 2.8381296218157614,
        r_min: 4.0, r_max: 12.0,
        d_phi: 9.779206072768423,
        d_t: 207.23492659254796,
        d_tau: 164.4392402966113,
    },
    // a = 0.9, p = 3.0, e = 0.4, prograde
    OracleOrbit {
        a: 0.9, energy: 0.8804361890523441, l_ang: 2.2453261305190804,
        r_min: 2.142857142857143, r_max: 5.0,
        d_phi: 21.269499929735133,
        d_t: 134.72941914196096,
        d_tau: 69.55777002144629,
    },
    // a = 0.9, p = 12.0, e = 0.3, retrograde
    OracleOrbit {
        a: 0.9, energy: 0.9681271635588824, l_ang: -4.35775928414171,
        r_min: 9.23076923076923, r_max: 17.142857142857142,
        d_phi: -11.385790150632882,
        d_t: 504.6805638825578,
        d_tau: 438.13403411011717,
    },
    // a = 0.998, p = 2.4, e = 0.3, prograde
    OracleOrbit {
        a: 0.998, energy: 0.8277831177864031, l_ang: 1.862915481753444,
        r_min: 1.846153846153846, r_max: 3.428571428571429,
        d_phi: 18.303020029040454,
        d_t: 89.16278805317573,
        d_tau: 38.8001431909987,
    },
    // a = 0.0, p = 8.0, e = 0.5, prograde
    OracleOrbit {
        a: 0.0, energy: 0.9597148699373931, l_ang: 3.6706517419289897,
        r_min: 5.333333333333333, r_max: 16.0,
        d_phi: 13.253105361892734,
        d_t: 377.43849222052717,
        d_tau: 311.18320594876747,
    },
];
